# Network config
audionet:
  audionet_name: TIGER
  audionet_config:
    out_channels: 128
    in_channels: 256
    num_blocks: 4
    upsampling_depth: 5
    win: 640
    stride: 160
    num_sources: 2

# Loss config
loss:
  train:
    loss_func: PITLossWrapper
    sdr_type: pairwise_neg_snr
    config:
      pit_from: pw_mtx
      threshold_byloss: false
  val:
    loss_func: PITLossWrapper
    sdr_type: pairwise_neg_sisdr
    config:
      pit_from: pw_mtx
      threshold_byloss: false

# Training config
training:
  system: AudioLightningModule
  gpus: [1,2,3,4]
  parallel: ddp
  epochs: 500
  early_stop:
    monitor: val_loss/dataloader_idx_0
    mode: min
    patience: 20
    verbose: true
  SpeedAug: False
  
# Optim config
optimizer:
  optim_name: adam
  lr: 0.001
  weight_decay: 0

# Sche config
scheduler: 
  sche_name: ReduceLROnPlateau
  sche_config:
    patience: 10
    factor: 0.5

# Data config
datamodule:
  data_name: LibriUMixModuleRemix
  data_config:
    train_dir: DataPreProcess/unknown_speaker/LibriUmix/train-100
    valid_dir: DataPreProcess/unknown_speaker/LibriUmix/dev
    test_dir: DataPreProcess/unknown_speaker/LibriUmix/test
    n_src: 3
    sample_rate: 16000
    segment: 3.0
    normalize_audio: false
    batch_size: 2
    num_workers: 8
    pin_memory: true
    persistent_workers: false

exp:
  exp_name: TIGER-LibriUMix